### ISSUE TITLE
Missing `alt` attribute

### ISSUE THREAD

**Issue by marcysutton** [fpapado/react-lazy-images#1]
I see a lot of stuff in the API, but no `alt` attribute. This is a mission-critical one for a more accessible component. 

Some usage tips:
- `alt` takes a string value with the content. 
- If the image is decorative, the attribute value should be empty to ensure the filename is not read (`alt=""`)

Here's a decision tree for choosing good alt text: https://www.w3.org/WAI/tutorials/images/decision-tree/

**Comment by fpapado** [comment]
The README, Storybook and Codesandbox examples are now updated.
Took me a bit longer because placeholder services do not keep the images consistent between calls.
Thus, to avoid an arbitrary `alt` description, I had to dig through my photos :D

(I could not avoid "A portrait of Bill Murray" in cases where the image is truly a random. I see this `alt` pattern every so often in articles online where they take a photo of the interviewee).

This leaves the API issue open. I would value your input on this once you have the time.

It is late here and I have to wake up in a few hours, but I promise to get back to this in the morning.

**Comment by marcysutton** [comment]
> I am now working on adding alt to the examples, since they show concrete use cases. I think this would set a good precedent for people following them.

Yes, I agree that would be a great way to nudge developers towards accessibility! And thanks for the quick response. 

Is it typically the same image being preloaded? I'm wondering if you could simplify the API a bit to make it easier and more DRY when including an `alt` attribute:

```
<LazyImage
  src="/img/porto_buildings_large.jpg"
  alt="Buildings with tiled exteriors, lit by the sunset."
  placeholder={() => <img src="/img/porto_buildings_lowres.jpg" />}
  actual={() => <img src="/img/porto_buildings_large.jpg" />}
/>;
```
In that snippet, I've moved `alt` to the LazyImage component in the expectation that it would be forwarded on to the two image tags...but I haven't dug into your API enough to know if that's appropriate. Perhaps you could check for `alt` on `LazyImage` and if it doesn't exist, check on the individual `img` tags? That way it could still be flexible.

**Comment by fpapado** [comment]
This makes sense, and it means that both `src` and `alt` can be consistent and less prone to repetition/typing mistakes. It helps enforce both the accessibility and loading properties. 

I have added a PR for this and expect it to be landing in the next version, 0.9 :tada: 
(Once I've had some rest and can press the 'publish' button confidently).

Due to how React handles these render callbacks, it is not feasible to implicitly forward those attributes, but the extra typing is minimal, and just as flexible.

```jsx
<LazyImage
  src="/img/porto_buildings_large.jpg"
  alt="Buildings with tiled exteriors, lit by the sunset."
  placeholder={({ alt }) => (
    <img src="/img/porto_buildings_lowres.jpg" alt={alt} />
  )}
  actual={({ src, alt }) => <img src={src} alt={alt} />}
/>;
```
