### ISSUE TITLE
2 easily fixable errors in the *.d.ts files in dist

### ISSUE THREAD

**Issue by flq** [fpapado/react-lazy-images#13]
Hi, in both `LazyImage.d.ts` and `LazyImageFull.d.ts` `react` is imported incorrectly.
Instead of 

```ts
import React from "react";
```

it should read 

```ts
import * as React from "react";
```

The 2 offending lines are spit out in e.g. a webpack build, and it breaks auto-complete in VS Code. Fixing it manually makes the auto-completion appear.

I am not sure how the **d.ts**. files are generated, otherwise I would have made a PR, but here you go.

**Comment by flq** [comment]
ok, I just saw that those lines are _as-is_ in your source code and now I am confused because I _don't_ have a default export from react…

**Comment by fpapado** [comment]
Hi, @flq! Thanks for getting in touch.

To clarify, does the build work? 

As for the types/import method, it is actually a Typescript configuration issue rather than a declaration issue per se.

Copying over from my response on another repo:

The "default import is undefined" is usually a `tsconfig.json` issue, rather than a definition issue. Out of the box, Typescript does not handle default imports the same way as, say, Babel, which is why you have to use the faux namespace (`* as...`) import.

However, there is a tsconfig.json option to specify the `import DefaultName from 'package'` behaviour:

```json
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true
  }
}
```

Fwiw, I tend to use this in all my projects, since it's less special syntax to remember, and more in line with Babel :)

The TS2.7 notes have a good explanation, under "Support for import d from "cjs" form CommonJS modules with --esModuleInterop":
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html

## Type Compatibility
The annoying part about Typescript is that it deprecates things in minor versions, and afaik also has no way of marking "versions" for declaration files, or even their configuration. In this case, I guess that your project does not use "esModuleInterop", and Typescript applies your own project's config instead of the one that the declaration was generated with. I am also a bit surprised that VS Code does not auto-bridge this discrepancy, since their TS integration is pretty tight.

I am not sure what the solution is here, apart from encouraging more people to use "esModuleInterop" atm. I am curious what TS type repositories such as [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) have as a guideline in these situations. It could be worth going over prior art and seeing if there is a better way for this.

**Comment by flq** [comment]
Thank you for your detailed explanation of this set-up. Since we have full control over our codebase, we have made the modification in the tsconfig.json and changed our import statements accordingly. If anything, it's less stuff to type :)

Thanks again, feel free to close the issue

**Comment by fpapado** [comment]
No worries :) I hope Typescript considers making this the default some day. Will add a backlog item to investigate TS versioning schemes for types, in case it comes up again in the future.
