### ISSUE TITLE
Not using specific version on dependecies can cause build failed

### ISSUE THREAD

**Issue by dehamzah** [fpapado/react-lazy-images#14]
I see that this package depends on package `react-intersection-observer`, but this may cause the build failed if you didn't set the specific version on your dependencies i think. Recently `react-intersection-observer` has publish new version, and my create-react-app project failed to build caused by this peer dependencies (i already put the issue on [there](https://github.com/thebuilder/react-intersection-observer/issues/116) )

I am trying to install the react-intersection-observer v6.1.1 manually, and it fix the build in my local, but didn't fix it on my netlify build. I also trying to fork the package and try to test it in my package.json using this command, to see is it really caused by this `^` on dependency version.

```
npm install dehamzah/react-lazy-images#master
```

But it failed to found the package when i start my cra project.

**Comment by thebuilder** [comment]
This issue is resolved in the latest version of `react-intersection-observer. You can use the [yarn resolutions](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/) feature to force a specific version if you run into an issue like this again.

**Comment by fpapado** [comment]
Hi, @dehamzah!

I see what you mean, it can be frustrating when things are changing from below.
In many ways, this is an ecosystem issue rather than an individual one.

I think there is value in having semantically-compatible dependency ranges for libraries, and locking dependencies for applications. I find that locking dependencies in applications is worth it, whereas locking down dependencies in libraries can be more problematic.

## Libraries
Using major-compatible ranges for libraries (`^` will not match a major version) is typically a good thing, because it allows sharing the dependency in an application. For example, if your application uses `react-intersection-observer@6`, and you also use `react-lazy-images`, then you will most likely get only one copy! Conversely, imagine if every library was declaring exact dependencies for their own dependencies, we would have so much duplication. I also find that patches are more valuable, and locking down dependencies would mean you have to wait for the library "higher up" to update before getting it.

Of course, this places some emphasis on semantic versioning (semver) not to break. There are various ways to capture this, some more durable and some less. More often than not, fixing it is a short PR/issue away. I like using `react-intersection-observer` precisely because @thebuilder is so responsive - 6.2.1 is already out to fix it :) I don't think there is a situation where `6.2.0` will be resolved now that a patch version on top, unless  locked as such.

## Applications
For applications, both npm and yarn offer lockfiles (`package-lock.json` and `yarn.lock`) respectively, that capture not just the direct dependencies, but also the resolved versions of the full dependency graph.
Npm did not have this until version `5.x` if I remember correctly.
Yarn also offers more manual resolution mechanisms for fixing things, though I haven't had to use it in an application yet.

Yarn's page on manual resolution provides a good [explanation of how both exact and broad dependencies can break sometimes](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/#toc-why-would-you-want-to-do-this). Perhaps it is more concise than my explanation here.

I don't have a concrete change, but I hope this gives some insight into the reasoning.

Let me know if there is anything I can help with :)

**Comment by dehamzah** [comment]
thankyou @thebuilder for the fix on `react-intersection-observer` it already works now.

thankyou too @fpapado for the explanation, i learn a lot from your explanation.

i think i have no more issue on this.
