### ISSUE TITLE
fade in

### ISSUE THREAD

**Issue by armmmo** [fpapado/react-lazy-images#18]
hi,
is fade in supported? how would i go about implementing it?

after the debouncing, the image shows up too fast.

thanks

**Comment by fpapado** [comment]
Hi, @armmmo!

It's a bit hard to tell without a concrete example, because I do not know how you have set up the placeholder and actual image components. Generally speaking, with way the library defers rendering to the caller, it should definitely be possible to implement fade-in on top.

The examples on Codesandbox have some more concrete components that utilise fade-in via a class and CSS keyframes: https://codesandbox.io/s/jnn9wjkj1w.
You would want to look into the `opinionatedComponents.js`, and line 53 onward in `index.scss`.

Let me know if you have a different scenario in mind. Hope this helps :)

**Comment by fpapado** [comment]
Hi @armmmo, I'll go ahead and close this issue since it has been idling for a while :)
