### ISSUE TITLE
Documentation for background-images

### ISSUE THREAD

**Issue by geochanto** [fpapado/react-lazy-images#24]
You mention that component supports background-images. Can you provide any documentation / sample code on how to do so? For example, divs or any other elements with inline CSS background-image property.

**Comment by fpapado** [comment]
Hi, @geochanto!
I think this code sample from the stories docs fits what you describe:
https://github.com/fpapado/react-lazy-images/blob/2ec1f3e8af423295b23b7dbf05c6ab1cd30f6982/stories/LazyImage.story.tsx#L281

And on the [online demo version](https://fpapado.github.io/react-lazy-images/?selectedKind=LazyImage&selectedStory=Background%20image&full=0&addons=1&stories=0&panelRight=1&addonPanel=storybook%2Factions%2Factions-panel).

The main idea:
- you can provide the src for the image to be loaded when in view
- you can assign the react ref to the relevant container element
- when it is in view and the image has loaded, the `actual part will render; instead of an `img`, we render a div with a background image

Does this do what you are looking for? I might have missed something, happy to follow up if so :)

**Comment by geochanto** [comment]
Awesome, exactly what I needed. Thanks a lot!

**Comment by fpapado** [comment]
Perfect, I'll go ahead and close this issue, for housekeeping purposes. Feel free to re-open or make a new one if something comes up.
