### ISSUE TITLE
Add support for loadEagerly or Intersection Observer rootTarget

### ISSUE THREAD

**Issue by wgottschalk** [fpapado/react-lazy-images#5]
#### Use case:
I want to lazy load images inside of an image carousel. Specifically given 3 images: image0, images1, images2 where image0 is initially displayed in the viewport, I want to load only image0 and image1 initially. Then after the user transitions to image1 in the viewport, I want to load image2 (which is still not in view).

#### Possible solution: 
I noticed that with the intersection observer you can designate a root element either via a DOM node or element id string.  However no prop exists currently to target that node.

#### Another solution: 
Don't get fancy and just eagerly load all the images

I noticed in the source code that there's a prop for [loadEagerly](https://github.com/fpapado/react-lazy-images/blob/b735a3c4080177e42dce3fe98b30e7fc39ab0f63/src/LazyImageFull.tsx#L20). However, when I try and look thought the source code, I noticed that there's no reference to that prop.

Let me know how I can help contribute to this awesome project!

**Comment by fpapado** [comment]
Hi! Thanks for opening this. I appreciate starting with the use case. A big motivation when making this library was to focus on the use cases, and this helps.

On concrete points:

**loadEagerly**
You found a bug! I can trace this back to when I split `LazyImage` and `LazyImageFull`, and it seems I forgot `loadEagerly`. A reminder that I should expedite the automated testing. I have now fixed it and it should be landing in v0.9.1 :tada:

**Image Carousels**
As a general note, lazy loading with the default root (the viewport) should work with horizontal scrolling out of the box. [There is a demo on storybook](https://fpapado.github.io/react-lazy-images/?selectedKind=LazyImage&selectedStory=Horizontal%20scroll&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybook%2Factions%2Factions-panel). I also went ahead and set up a [basic carousel on Codesandbox to test](https://codesandbox.io/s/m4kzo330vp) (you might need to resize the browser to make the carousel work; it is buggy in their latest version).

If I understand correctly, you are asking about preloading the next image in the carousel in advance, instead of only loading when it is in the viewport. I am having trouble understanding how a custom `root` would help. Would you be able to make a small demo with the carousel in question? I am open to adding `root`, but want to see the use case first. It would help verify that the solution works, and also offer a good example for the docs :)

Some alternatives:
- I wonder if leaving the lazy behaviour with a placeholder or loading state would be preferable to `loadEagerly`. It's a design choice, I suppose.
- If your carousel is such that the images are always present (like the storybook example), then I think a horizontal `rootMargin` would give you a simple preload. Something like `intersectionObserverProps={{rootMargin: "100px 50px"}}`, perhaps?

**Comment by fpapado** [comment]
I should also expedite adding a "developing locally" part of the docs. It is a bit fiddly due to having to use a custom version of [microbundle](https://github.com/developit/microbundle), but I understand it would help debug issues locally.

**Comment by geochanto** [comment]
@fpapado does this also work with a coursel when using background-images? I'm trying to preload previous/next slide background-images with `observerProps`, but `actual` images still load only after coming into the viewport. I tried setting really large rootMargin like 10000px, but it had no effect.

**Comment by fpapado** [comment]
@geochanto, I think it depends on how the carousel hides the next/previous slide.

I can think of two scenarios, depending on the slides:
1. If they exist in the DOM already (for example, by using horizontal scrolling), they most likely will get picked up by the IntersectionObserver, and be loaded in advance.
2. If the slides only exist on the DOM conditionally (such as with internal state), then the soonest the IntersectionObserver/this library will pick them up, is when they get added.

I think scenario 2. might be what you are experiencing here.
I tweaked the demo and starter Codepen to verify this:
https://codesandbox.io/s/reactlazyimagesquickstart-mv8io

Could you tell me if that matches what you are running into?

I can't think of a good solution off the top of my head, because we'd have to dig into what the slides implementation exposes, and it would likely involve more domain-specific handling, rather than something at the library level. Still I hope this points you in some direction :)

**Comment by geochanto** [comment]
@fpapado you are exactly right. I checked and it seems non-active slides only have a wrapper element rendered, but not internal elements including the div with background image. What I'm using is this: https://alvarotrigo.com/react-fullpage/ . I'll dig into their documentation to see if I can do something about that. Sadly their own lazy-loading didn't work on background images so that's why I turned to your plugin. Meanwhile if you happen to have any suggestions, would be much appreciated. Thanks for your responses!

**Comment by geochanto** [comment]
@fpapado sorry I was wrong with my previous comment. The slides **do exist** in the DOM, somehow it was acting up yesterday. 

The implementation is that slides are navigated with previous/next arrows, which apply `transform: translate3d` CSS to the **slides wrapper**, moving the wrapper left or right. 

So do I have any course of action in this case? I do have a built-in callback onSlideChange, so if there is any method I can call on react-lazy-load to load the next image, that should work. BTW, I'm using CSS background-images rather than <img>

**Comment by fpapado** [comment]
Hmm, one thing I would consider is setting `loadEagely` on the images of the next slide, after onSlideChange. It might need some state management/tracking of the indices, and it might depend on the setup, but I think that could work.
