### ISSUE TITLE
Overly verbose setState

### ISSUE THREAD

**Issue by tvthatsme** [fpapado/react-lazy-images#7]
Less of an issue and more of an FYI - as encouraged by your feedback.md 😀 

I am authoring a library similar to yours (but without intersection-observer) so was digging into your source code to see your approach. Looks nice and thanks for some inspiration! I did notice that a lot of your setState code goes something like this:

```js
this.setState((state, props) => ({
  ...state,
  imageState: ImageState.Loading
}));
```

According to the React docs [state updates are merged](https://reactjs.org/docs/state-and-lifecycle.html#state-updates-are-merged) so you don't have to spread state when you set it. I think you could actually just do something like this:

```js
this.setState({
  imageState: ImageState.Loading
});
```

I could raise a PR but the project doesn't have any tests so I don't want to accidentally break something.

**Comment by fpapado** [comment]
Hi, @tvthatsme! 

I am glad you're finding the code useful, I'd be happy to hear more about what you're building :)

The `setState` functional form presented is intentional. While it is true that React auto-merges the calls, it only does a shallow merge
> The merging is shallow, so this.setState({comments}) leaves this.state.posts intact, but completely replaces this.state.comments.

While this is not a problem per se, the moment you have objects in your state, the auto-merge is harder to reason about. 

The `setState` call also needs to change to the long-hand if you ever depend on the previous state. The long form can allow you to extract the update functions without it seeming magical (see e.g. https://twitter.com/dan_abramov/status/824308413559668744). 

For that, and to make the "keep past, merge next on top" more explicit, I always use the the long-hand / functional `setState` variant. (I sometimes see folks naming `state` as `prevState` to make it more obvious.) The extra typing is minimal, and it saves me having to remember edge cases and multiple forms. 

Hope this helps!

**Comment by tvthatsme** [comment]
Ahh yeah that makes sense. Thanks for explaining! I had forgotten that the setState is only a shallow merge.

Bonus points for the Dan Abramov tweet 😁
